accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView
app_name = 'accounts'

urlpatterns = [
    
    path('home/', views.indexView, name = 'home'),
    path('dashboard/', views.dashboardView, name = 'dashboard'),
    path('login/',LoginView.as_view(), name='login_url'),
    path('regist/', views.regist, name='regist'),
    path('logout/',LogoutView.as_view(next_page ='accounts:home' ), name='logout'),

]

status/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView
app_name = 'status'

urlpatterns = [
    path('', views.create_status, name='create_status'),
    path('story7/', views.story7, name='story7'),
    path('books/', views.books, name = 'books'),
    

]

story6/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('status.urls')),
    path('accounts/', include('accounts.urls'))
    
]

accounts/models.py
from django.db import models

# Create your models here.

status/models.py
from django.db import models
from datetime import datetime

class Status(models.Model):
    status = models.CharField(max_length = 300)
    updated_at = models.DateTimeField(auto_now_add=True, editable=False, null=False, blank=False)
    

status/forms.py
from django import forms
from .models import Status

class StatusForm(forms.ModelForm):

    status = forms.CharField(widget=forms.TextInput(attrs={
        "class" : "form-control",
        "placeholder" : "Tell me how you feel!",
    }))

    class Meta:
        model = Status
        fields = ['status']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def indexView(request):
    return render(request,"index.html")

@login_required
def dashboardView(request):
    return redirect('status:create_status')

def login(request):
    return render(request,"login.html")

def regist(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:login_url')  
    else:
        form = UserCreationForm()
    return render(request,"registration/regist.html", {'form':form})

status/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Status
from . import forms

def create_status(request):
    
    if request.method == "POST":
        form = forms.StatusForm(request.POST or None)
        if form.is_valid():
            form.save()
            status = Status.objects.all().order_by('-id')
            response = {'status': status, 'title': 'List', 'form':form}
            return render(request, "landingpage.html", response)
    else:
        form = forms.StatusForm()
        status = Status.objects.all().order_by('-id')
        response = {'status': status, 'title': 'List', 'form':form}
    return render(request, "landingpage.html", response)

def story7(request):
    return render(request, "story7.html")

def books(request):
    return render(request,"books.html")

accounts/templates/dashboard.html
{% extends 'index.html' %}

{% block content %}
    <h1 class='jumbotron'>Welcome, {{user.username}} </h1>
{% endblock %}

accounts/templates/index.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Simple Auth System</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/style2.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">    
</head>
<body class="home newsletter">
    {% block content %}
        <h1>Welcome to Rani's Site</h1>
        {% if user.is_authenticated %}
            <a href="{% url 'accounts:logout' %}">Logout</a>
            {% else %}
            <a href="{% url 'accounts:login_url' %}">Login</a>
            <a href="{% url 'accounts:regist' %}">Register</a>
        {% endif %}
    {% endblock %}
</body>
</html>

accounts/templates/logout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Page Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="main.css">
    <script src="main.js"></script>
</head>
<body>
    
</body>
</html>

status/templates/books.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=Kurale|Laila|Shrikhand&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Cinzel|Patua+One&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css">
    <link rel="stylesheet" href="{% static 'css/bookstyle.css' %}">

    <title>Books Library</title>
</head>

<body>
<!-- NAVBAR -->
<nav class="navbar navbar-expand-lg navbar-light nav-home">
        <a class="navbar-brand"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
            
        <div class="collapse navbar-collapse " id="navbarNavAltMarkup">
            <div class="navbutton navbar-nav">
                <a class="nav-item nav-link active" href="{% url 'status:create_status' %}">Status</a>
                <a class="nav-item nav-link" href="{% url 'status:story7' %}">Profil</a>
                <a class="nav-item nav-link" href="{% url 'status:books' %}">Books</a>
                
                {% if user.is_authenticated %}
                    <a class="nav-item nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                {% else %}
                    <a class="nav-item nav-link" href="{% url 'accounts:home' %}">Login</a>
                {% endif %}
                
            </div>
        </div>
    </nav>
<div class='bebas'>
    <div class = "newsletter">
        <h1>Search
            <span>your Favorite Books</span>
        </h1>
        <p>Test</p>
        <div class="search-box">
            <input class="search-txt" type="search" id="searchField" name="" value="" placeholder="Type to search">
            <button class="search-btn" type="button" name="button"><i class="fas fa-search"></i></button>
        </div>
        
        <table class="table" id="tableRani"></table>
    </div> 
    
</div>
<script src="https://code.jquery.com/jquery-1.11.3.js"></script>
<script src="{% static 'js/script2.js' static %}"></script>

</body>
</html>

status/templates/landingpage.html
<!DOCTYPE html>
{% load static %} 
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=Kurale|Laila|Shrikhand&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <title>Status</title>


</head>
<body class="home">
    
<!-- NAVBAR -->
    <nav class="navbar navbar-expand-lg navbar-light nav-home">
        <a class="navbar-brand"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
            
        <div class="collapse navbar-collapse " id="navbarNavAltMarkup">
            <div class="navbutton navbar-nav">
                <a class="nav-item nav-link active" href="{% url 'status:create_status' %}">Status</a>
                <a class="nav-item nav-link" href="{% url 'status:story7' %}">Profil</a>
                <a class="nav-item nav-link" href="{% url 'status:books' %}">Books</a>

                {% if user.is_authenticated %}
                    <a class="nav-item nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                {% else %}
                    <a class="nav-item nav-link" href="{% url 'accounts:home' %}">Login</a>
                {% endif %}
            </div>
        </div>
    </nav>


    {% if user.is_authenticated %}
        <h1 class="halo">Hello, how are you {{user.username}}? </h1>
    {% else %}
        <h1 class="halo">Hello, how are you? </h1>
    {% endif %}

    <form class="css" action="{% url 'status:create_status' %}" method="post">
        
        {% csrf_token %}
        <div class="form-row">
            <div class="col-sm-1"></div>
            <div class="form-group col-sm-10 jumbotron " style="background: whitesmoke">
                <div class="form-row">
                <input type="submit" class="btn btn-primary float-right text" value="Add" id="submit">
            </div>
                {% for fields in form %}
                    <!-- {{ fields.label_tag }} -->
                    <br>
                    {{ fields }}
                {% endfor %}
            
            </div>
       
        </form>
    </div>
   
        <div class="row">
        {% for x in status %}
        <div class="col-sm-4 formstatus stat">
            <h1>{{x.status}}</h1>
            <p>{{x.updated_at}}</p>
        </div>
        {% endfor %}
    </div>



</body>
</html>

status/templates/story7.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=Kurale|Laila|Shrikhand&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    
    <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/jquery-1.10.2.js"></script>
    <script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
    <script src="{% static 'js/script.js' %}"></script>
    
    <title>Rani Aprilia Astrianty</title>
</head>


<body class='newpage'> 
    
    <section>
        <h1 class="title">Hello, my name is Rani</h1>
        
        <div class="row pic">
                <img src="{% static 'images/avatar1.png'%}" class = "img-fluid pic" alt="ava">
            </div>
    
        <p class='text-center desc'>I am 19 years old. I am currently studying as a second-year<br>
        student at the Faculty of Computer Science, majoring in<br>
        Information System at Universitas Indonesia.<br>
        I’am a very responsible, thorough, and sociable person.</p>
    </section>

    <ul>
        <li>
            <span>Click Me!</span>
            <span>Click Me!</span>
        </li>
    </ul>
    
    <script type="text/javascript">
        $(document).ready(function(){
            $('ul').click(function(){
                $('ul').toggleClass('active')
                $('section').toggleClass('dark')
            })
        })
    </script>

<!-- NAVBAR -->
<nav class="navbar navbar-expand-lg navbar-light nav-home">
        <a class="navbar-brand"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
            
        <div class="collapse navbar-collapse " id="navbarNavAltMarkup">
            <div class="navbutton navbar-nav">
                <a class="nav-item nav-link active" href="{% url 'status:create_status' %}">Status</a>
                <a class="nav-item nav-link" href="{% url 'status:story7' %}">Profil</a>
                <a class="nav-item nav-link" href="{% url 'status:books' %}">Books</a>
                {% if user.is_authenticated %}
                    <a class="nav-item nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                {% else %}
                    <a class="nav-item nav-link" href="{% url 'accounts:home' %}">Login</a>
                {% endif %}
            </div>
        </div>
    </nav>

<div class="row"></div>
<div class="row">
    <div class="col-4"></div>
    <div class="col-4 row-mar">
        <div id="jQuery_accordion">
            <h3>Current Activities</h3>
                <p class="text-style">Struggling to get S.kom degree behind my name</p>
            
            <h3>Organizations and Commitees</h3>
                <p class="text-style">
                    1. Sponsorship staff at CGT 2019<br>
                    2. Fundraising staff at Compfest 11<br>
                    3. Secretary staff (to be) for Compfest 12
                </p>
            
            <h3>Achievements</h3>
                <p class="text-style"> Survive until today</p>
          </div>
      </div>
    </div>
</div>



</body>
</html>